class DemoPageLocators(object):
    DEPARTURE_CITY_DROPDOWN = "//select[@name='fromPort']"
    DESTINATION_CITY_DROPDOWN = "//select[@name='toPort']"
    SEARCH_BUTTON = "//input[@type='submit']"
    FLIGHT_ROWS_LENGTH = "//table[@class='table']/tbody/tr"
    CHOOSE_FIRST_FLIGHT_BUTTON = "/html/body/div[2]/table/tbody/tr[1]/td[1]/input"
    INPUT_NAME = "//input[@name='inputName']"
    INPUT_ADDRESS = "//input[@name='address']"
    INPUT_CITY = "//input[@name='city']"
    INPUT_STATE = "//input[@name='state']"
    INPUT_ZIP_CODE = "//input[@name='zipCode']"
    INPUT_CARD_NUMBER = "//input[@name='creditCardNumber']"
    INPUT_CARD_NAME = "//input[@name='nameOnCard']"
    PURCHASE_BUTTON = "/html/body/div[2]/form/div[11]/div/input[@type='submit']"
    PURCHASE_SUCCESS_MESSAGE = "/html/body/div[2]/div/h1"
